#source 'https://github.com/CocoaPods/Specs.git'

target 'ARCurveSlider', :exclusive => true do
  pod "ARCurveSlider", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ARCurveSlider", :path => "../"

  
end
